# Generated by Django 4.1.7 on 2023-08-23 11:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movie_app", "0007_alter_movie_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="budget",
            field=models.IntegerField(blank=True, default=1000000),
        ),
    ]
